# Generated by Django 3.1a1 on 2020-06-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200615_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='my_skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50)),
                ('progress', models.CharField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='main_win',
            name='about_me',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main_win',
            name='photo_me',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
