# Generated by Django 3.1a1 on 2020-06-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_my_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('text', models.TextField()),
            ],
        ),
    ]
